### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by Olivialyt** [zzc-1998/GMS-3DQA#2]
Hello, could you please upload the checkpoints: swin_tiny_patch4_window7_224_22k.pth? The checkpoints I found from huggingface is not matched with your network.

**Comment by zzc-1998** [comment]
Hello, the checkpoint can be downloaded at https://1drv.ms/u/s!AjaDoj_-yWgggttCGTboscTuOExeVQ?e=ECpGtR.
